services:
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prod

  api:
    build:
      target: prod
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/prod?schema=public
    command: yarn start:prod
