version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - cache:/data
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nest?schema=public
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
volumes:
  cache:
  pgdata:
