version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - cache:/data
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
volumes:
  cache:
  pgdata:
